In [2]:
import numpy as np

In [ ]:
np.__version__

In [ ]:
#구글 코랩 + 구글 내드라이브 => 연동
# AWS 사용

In [ ]:
shape : 배열의 구조
16*16 컬러사진은 rgb(28,28,3) 형식 = (행, 열, 채널)

In [ ]:
arr=[1,2,3,5,7]

In [ ]:
#arr 리스트 안에 있는 요소를 어레이로 만들기
np.array(arr)

In [6]:
myarr=np.arange(5)
myarr
np.arange(1,6,2)

array([1, 3, 5])

In [8]:
li=list(range(10))

%time = 
매직 타임, 코드 실행하는데 걸린 시간

In [9]:
%time for _ in range(10): li2=[x*2 for x in li]

li2

Wall time: 0 ns


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
#모든 요소에 대해 연산할때 np쓰면 한꺼번에 됨 (R특성을 파이썬에 적용=벡터에 연산함)

%time for _ in range(10): arr2=myarr*2

arr2

In [ ]:
#n차원 배열 객체(대량의 데이터 집합 저장 가능)

In [213]:
z=np.random.random((2,3)) #0에서 1사이의 난수로 행렬구조
z.min()
z.mean()

0.4041786944471819

In [75]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [10]:
#2행 3열의 난수들 (평균이 0 표준편차가 1인 정규 분포를 따르는 수들 중)
data=np.random.randn(2,3)
data

array([[ 0.83680857,  0.59423486, -1.59190862],
       [ 0.71319628, -0.36224603, -0.07393928]])

In [76]:
data*100

data+data 

array([[ 1.67361713,  1.18846972, -3.18381725],
       [ 1.42639256, -0.72449206, -0.14787856]])

numpy 배열은 모든 원소가 같은 자료형이어야 한다.

In [79]:
data.shape #dim

(2, 3)

In [125]:
data.dtype

dtype('float64')

In [84]:
arr=np.ones((2,3))
arr.shape
arr.ndim
arr.dtype

dtype('float64')

In [ ]:
data1=[6,7.5,8,0,1]

arr1=np.array(data1)
arr1 #모두 실수로 변환됨

#### 요소 채우기
zeros =  0으로 채우기,
ones = 1로 채우기

In [78]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [77]:
np.zeros(10) #0으로 채우기

np.zeros((3,6)) #0으로 채운 행렬

np.ones((2,3))

np.ones(5)*5

array([5., 5., 5., 5., 5.])

arange함수 = range()와 같은 역할, 단 array로 생성

In [116]:
list(range(10)) #파이썬
np.arange(10) #넘파이

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
arr=np.arange(10)
arr.dtype
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
farr=arr.astype(np.float64) #실수 변환
farr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [90]:
data=np.arange(6)
data*data

array([ 0,  1,  4,  9, 16, 25])

In [92]:
array=np.array([[1,2],[3,4]])
array

array*array #행렬곱
array-array
array+array
array**2

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [93]:
#요소간 비교
ary=np.ones((2,2))
ary<array

array([[False,  True],
       [ True,  True]])

인덱싱, 슬라이싱

In [104]:
arr=np.arange(10)
arr[5:8]

arr[2]=10
arr

array([ 0,  1, 10,  3,  4,  5,  6,  7,  8,  9])

In [94]:
ar=np.arange(10,16)
ar2d=ar.reshape(2,3)
ar2d

array([[10, 11, 12],
       [13, 14, 15]])

In [95]:
ar2d[0][2]
ar2d[0,2]

12

In [127]:
#1~12까지 값을 갖는 (3,4,2) 3차원 배열
ar=np.arange(1,25)
arr=ar.reshape(3,4,2) #3행 4열 2채널=깊이=높이
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [113]:
#0~31까지의 array
arr=np.arange(32).reshape(4,2,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

__속성__과 __함수__는 사용되는 경우가 다르다.

In [116]:
arr.sum(axis=0)

array([[48, 52, 56, 60],
       [64, 68, 72, 76]])

In [134]:
v.ndim #속성, 3차원

3

In [146]:
v.sum(axis=None) #함수

496

In [143]:
v.sum(axis=0) #행 방향으로 요소 모두 더한 값

array([[48, 52, 56, 60],
       [64, 68, 72, 76]])

In [144]:
v.sum(axis=1) #열 방향으로 요소 모두 더한 값

array([[ 4,  6,  8, 10],
       [20, 22, 24, 26],
       [36, 38, 40, 42],
       [52, 54, 56, 58]])

In [145]:
v.sum(axis=2) #깊이 방향으로 요소 모두 더한 값

array([[  6,  22],
       [ 38,  54],
       [ 70,  86],
       [102, 118]])

In [119]:
arr=np.arange(11,20)
arr=arr.reshape(3,3)
arr

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [163]:
arr[:2,1:]

array([[12, 13],
       [15, 16]])

In [123]:
arr[2].shape

(3,)

In [120]:
arr[2,:].shape #1차원 구조

(3,)

In [121]:
arr[2:,:].shape #2차원 구조

(1, 3)

In [127]:
arr[:,:2].shape

(3, 2)

In [124]:
arr[:,:2]

array([[11, 12],
       [14, 15],
       [17, 18]])

In [203]:
arr[::-1] #역방향

array([[17, 18, 19],
       [14, 15, 16],
       [11, 12, 13]])

범위를 어떻게 주느냐에 따라 N차원 구조가 달라진다.
행이 1, 은 1차원.
1:2, 은 2차원.

In [172]:
arr[:,:3:2]

array([[11, 13],
       [14, 16],
       [17, 19]])

In [177]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

np.full() : 행렬을 만들고 5로 초기화

In [131]:
np.eye(3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

np.eye() :  단위행렬

In [136]:
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

np.empty() : 3행 2열의 쓰레기값(랜덤한 값)으로 초기화

In [147]:
a=np.array([[1,2,3],[4,5,6]])

np.ones_like() 구조만 따오고 내용은 1로 초기화

In [150]:
#a의 구조만 따오고 내용은 1로 초기화
np.empty_like(a)

array([[-1856051296,         340,           0],
       [          0,           1,           0]])

In [154]:
arr=np.ones((2,3))
arr.size

6

In [196]:
a.itemsize #4 byte (실수는 8byte)
a.size #6 요소개수
print('%d bytes' % (a.itemsize * a.size))

24 bytes


In [201]:
#크기가 10인 z배열 0으로 초기화 -> 5번째 1로 변경
z=np.zeros(10)
z[4]=1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [155]:
np.nonzero([1,2,0,0,3]) #0이 아닌 인덱스

(array([0, 1, 4], dtype=int64),)

In [225]:
#10행 10열 테두리는 1, 안에는 0 되도록
a=np.ones((10,10))
a[1:9,1:9]=0
a

Z=np.ones((10,10))
Z[1:-1,1:-1]=0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])